version: '3.8'

services:
  backend:
    build: .
    container_name: code-analysis-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - /home/kali/Desktop/Semgrep/semgrep-rules:/home/kali/Desktop/Semgrep/semgrep-rules
      - /home/kali/Desktop/synk:/home/kali/Desktop/synk
      - /tmp/code-analysis-uploads:/tmp/code-analysis-uploads
    environment:
      - DEBUG_MODE=True
      - HOST=0.0.0.0
      - PORT=8000
      - SEMGREP_RULES_PATH=/home/kali/Desktop/Semgrep/semgrep-rules/c/lang/security/
      - SNYK_PATH=/home/kali/Desktop/synk
      - CLANGTIDY_PATH=clang-tidy
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: code-analysis-frontend
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend